---

- name: Setup common prerequisites
  hosts: localhost
  gather_facts: false

  vars_files:
    - common/setup.yml

  tasks:
    - name: Include Controller configuration files
      tags: always
      ansible.builtin.include_vars:
        dir: controller

    - name: Call dispatch role for Controller configuration
      tags: always
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
