---

- name: Setup AAP Config-as-Code for Controller
  hosts: localhost
  gather_facts: false

  vars_files:
    - common/setup_controller.yml

  tasks:
    - name: Include Controller configuration files
      tags: always
      ansible.builtin.include_vars:
        dir: controller

    - name: Call dispatch role for Controller configuration
      tags: always
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch

    # - name: Include EDA configuration files
    #   tags: always
    #   ansible.builtin.include_vars:
    #     dir: eda

    # - name: Call dispatch role for EDA configuration
    #   tags: always
    #   ansible.builtin.include_role:
    #     name: infra.aap_configuration.dispatch
